version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: your_postgres_db
      POSTGRES_USER: your_pg_username
      POSTGRES_PASSWORD: your_pg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - mongo
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mongo-data:
  postgres-data:
