version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db


  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/demo?authSource=admin
    depends_on:
      - mongodb

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: your_postgres_db
      POSTGRES_USER: your_pg_username
      POSTGRES_PASSWORD: your_pg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - mongodb
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=demo
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongodb:27017/demo?authSource=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/your_postgres_db
      - SPRING_DATASOURCE_USERNAME=your_pg_username
      - SPRING_DATASOURCE_PASSWORD=your_pg_password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  mongo_data:
  postgres-data:
  pgadmin-data:
